### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Valiceemo** [dalhundal/sky-remote-cli#2]
when running from the CL i get the following:
`/usr/bin/env: node: No such file or directory`

running on a Rpi3, Jessie Lite

**Comment by dalhundal** [comment]
Do you have Node installed?

**Comment by Valiceemo** [comment]
nodejs is installed yes:
`pi@raspberrypi:~ $ sudo apt-get install nodejs
Reading package lists... Done
Building dependency tree
Reading state information... Done
nodejs is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
`

**Comment by dalhundal** [comment]
Does typing `which node` output a path to the nodejs binary?

If so, modify line 1 of the script to point to it.

For example if `which node` outputs 

`/some/path/to/node`

Replace line 1

`#!/usr/bin/env node`

With

`#!/some/path/to/node`

Sorry if this message is poorly formatted, typed on a phone.

Let me know how you get on.

**Comment by Valiceemo** [comment]
are we talking about node or nodejs?

`which node` outputs nothing

**Comment by dalhundal** [comment]
NodeJS

I think with most installs these days the command for NodeJS is `node`, however there may still be some where it is `nodejs`.

Does `nodejs -v` produce any output?

**Comment by Valiceemo** [comment]
yes `nodejs -v` outputs v0.10.29

**Comment by dalhundal** [comment]
Ah ok, it's been installed as `nodejs` instead of `node` then.

That's a pretty old version you have there - this will still work with it though if you don't want to upgrade.

You have a few options:

1) Change the first line to `#!/usr/bin/env nodejs`

2) Create a symlink pointing node to nodejs: `sudo ln -s /usr/bin/nodejs /usr/bin/node`

3) Install a more modern NodeJS

Option 3 is best, but 1 or 2 will do the job for now if you want a quick fix.

**Comment by dalhundal** [comment]
If you decide to upgrade here's some quick instructions on getting the latest NodeJS on your raspi3

http://thisdavej.com/beginners-guide-to-installing-node-js-on-a-raspberry-pi/#install-node

**Comment by Valiceemo** [comment]
ill try updating NodeJS now

thanks for taking the time to help
